services:
  - type: web
    name: barter-backend
    env: docker
    plan: free
    repo: https://github.com/VviratT/BarterSkills
    branch: main
    dockerfilePath: BarterSkillsBackend/Dockerfile
    buildFilter:
      paths:
        - BarterSkillsBackend/**
    envVars:
      - key: PORT
        sync: false
      - key: MONGODB_URI; ACCESS_TOKEN_SECRET; REFRESH_TOKEN_SECRET; CLOUDINARY_CLOUD_NAME; CLOUDINARY_API_KEY; CLOUDINARY_API_SECRET; GOOGLE_CLIENT_ID; GOOGLE_CLIENT_SECRET; CLIENT_URL; SESSION_SECRET; RAZORPAY_KEY_ID; RAZORPAY_KEY_SECRET; RAZORPAY_PLAN_MONTHLY; RAZORPAY_PLAN_YEARLY; QG_URL; HF_API_KEY; FRONTEND_URL
        sync: false

  - type: web
    name: barter-python
    env: docker
    plan: free
    repo: https://github.com/VviratT/BarterSkills
    branch: main
    dockerfilePath: BarterSkillsBackend/Dockerfile.python
    buildFilter:
      paths:
        - BarterSkillsBackend/qg_service.py
        - BarterSkillsBackend/Dockerfile.python
    envVars:
      - key: HF_API_KEY; WHISPER_CMD
        sync: false
